### ISSUE TITLE
Build fails on RHEL 7.3 without libuv-devel

### ISSUE THREAD

**Issue by omarkilani** [tatsushid/h2o-rpm#4]
Hi there,

Trying to rebuild this package on RHEL 7.3 fails as libh2o.so isn't built without libuv-devel present.

Adding a BuildRequires: libuv-devel to the libh2o package fixes this.

**Comment by tatsushid** [comment]
Thanks for reporting the issue.

First I added libh2o building on CentOS 7, there was no suitable libuv package for H2O requirement but in these days, it has been added to CentOS 7 EPEL repository.

I'll add a `BuildRequires` as your suggestion to SPEC file.

**Comment by omarkilani** [comment]
👍
